// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfL5rLyit_FpOqGqnA-mUQK2tKvuVO6cg',
    appId: '1:891516759798:web:5bbb8ade4688b9acc0c6d7',
    messagingSenderId: '891516759798',
    projectId: 'iiitr-nexus',
    authDomain: 'iiitr-nexus.firebaseapp.com',
    storageBucket: 'iiitr-nexus.appspot.com',
    measurementId: 'G-P9FK150LS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2TJebC3kFPE8iZuVZTzYYKzU-M4LYCik',
    appId: '1:891516759798:android:58449279b1260578c0c6d7',
    messagingSenderId: '891516759798',
    projectId: 'iiitr-nexus',
    storageBucket: 'iiitr-nexus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7xqRZz3UlNT8ApWZYBSCel4mlj4BZ9sU',
    appId: '1:891516759798:ios:ecf022515284f1a5c0c6d7',
    messagingSenderId: '891516759798',
    projectId: 'iiitr-nexus',
    storageBucket: 'iiitr-nexus.appspot.com',
    iosBundleId: 'com.example.iiitrnexus1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7xqRZz3UlNT8ApWZYBSCel4mlj4BZ9sU',
    appId: '1:891516759798:ios:ecf022515284f1a5c0c6d7',
    messagingSenderId: '891516759798',
    projectId: 'iiitr-nexus',
    storageBucket: 'iiitr-nexus.appspot.com',
    iosBundleId: 'com.example.iiitrnexus1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfL5rLyit_FpOqGqnA-mUQK2tKvuVO6cg',
    appId: '1:891516759798:web:0c8a386ef01dd1bcc0c6d7',
    messagingSenderId: '891516759798',
    projectId: 'iiitr-nexus',
    authDomain: 'iiitr-nexus.firebaseapp.com',
    storageBucket: 'iiitr-nexus.appspot.com',
    measurementId: 'G-LDV1CV1G90',
  );

}